package ca.teranet.pages.polaris;

import ca.teranet.pages.base.BasePage;
import net.serenitybdd.core.annotations.findby.FindBy;
import net.serenitybdd.core.pages.WebElementFacade;

public class OwnersPage extends BasePage {

	@FindBy(xpath = "//INPUT[@id='ApplyToAllBtnForOwners' and @value='Apply to Some']")
	public WebElementFacade ApplyToSome_WebButton;

	@FindBy(xpath = "//TR[normalize-space()='ADMINISTRATOR (Retired) ADMINISTRATOR - DE BONIS NON ADMINISTRATIS (Retired) ADMINISTRATOR WITH WILL ANNEXED (Retired) AUTHORIZED OFFICER (Retired) BENEFICIAL OWNER (Retired) CAPACITY: N/A (Retired) COMMITTEE (Retired) DIRECTOR, VETERANS LAND ACT (Retired) ESTATE TRUSTEE DURING LITIGATION ESTATE TRUSTEE WITH A WILL ESTATE TRUSTEE WITHOUT A WILL EXECUTOR (Retired) FIRM NAME GENERAL PARTNER JOINT ACCOUNT JOINT ACCOUNT (Retired) JOINT ACCOUNT, RIGHT OF SURVIVORSHIP JOINT TENANTS LIFE ESTATE LIFE TENANT (Retired) LIMITED PARTNERSHIP (Retired) MINISTER (OF THE CROWN) (Retired) MUNICIPAL OFFICER (Retired) OFFICIAL GUARDIAN PARTNER PARTNERSHIP (Retired) POWER OF APPOINTMENT (Retired) POWER OF ATTORNEY (Retired) PUBLIC GUARDIAN AND TRUSTEE PUBLIC TRUSTEE (Retired) REGISTERED OWNER REMAINDER REMAINDERMAN (Retired) REVERSIONER (Retired) TENANTS IN COMMON TO USES (Retired) TRUSTEE TRUSTEE FOR SALE (Retired) TRUSTEE IN BANKRUPTCY TRUSTEE, IN TRUST (Retired) French']/TD[3]/SELECT[1]")
	public WebElementFacade Capacity2_WebList;

	@FindBy(xpath = "//TR[2]/TD[1]/INPUT[1]")
	public WebElementFacade CopyFromParentPIN_WebButton;

	@FindBy(xpath = "//TABLE[@id='messages']")
	public WebElementFacade ErrorMsg_WebTable;

	@FindBy(xpath = "//TR[normalize-space()='ADMINISTRATOR (Retired) ADMINISTRATOR - DE BONIS NON ADMINISTRATIS (Retired) ADMINISTRATOR WITH WILL ANNEXED (Retired) AUTHORIZED OFFICER (Retired) BENEFICIAL OWNER (Retired) CAPACITY: N/A (Retired) COMMITTEE (Retired) DIRECTOR, VETERANS LAND ACT (Retired) ESTATE TRUSTEE DURING LITIGATION ESTATE TRUSTEE WITH A WILL ESTATE TRUSTEE WITHOUT A WILL EXECUTOR (Retired) FIRM NAME GENERAL PARTNER JOINT ACCOUNT JOINT ACCOUNT (Retired) JOINT ACCOUNT, RIGHT OF SURVIVORSHIP JOINT TENANTS LIFE ESTATE LIFE TENANT (Retired) LIMITED PARTNERSHIP (Retired) MINISTER (OF THE CROWN) (Retired) MUNICIPAL OFFICER (Retired) OFFICIAL GUARDIAN PARTNER PARTNERSHIP (Retired) POWER OF APPOINTMENT (Retired) POWER OF ATTORNEY (Retired) PUBLIC GUARDIAN AND TRUSTEE PUBLIC TRUSTEE (Retired) REGISTERED OWNER REMAINDER REMAINDERMAN (Retired) REVERSIONER (Retired) TENANTS IN COMMON TO USES (Retired) TRUSTEE TRUSTEE FOR SALE (Retired) TRUSTEE IN BANKRUPTCY TRUSTEE, IN TRUST (Retired) French']/TD[4]/INPUT[1]")
	public WebElementFacade French2_WebCheckBox;

	@FindBy(xpath = "//input[@id='ownersForm.add']")
	public WebElementFacade MoreNames_WebButton;

	@FindBy(xpath = "//TR[normalize-space()='ADMINISTRATOR (Retired) ADMINISTRATOR - DE BONIS NON ADMINISTRATIS (Retired) ADMINISTRATOR WITH WILL ANNEXED (Retired) AUTHORIZED OFFICER (Retired) BENEFICIAL OWNER (Retired) CAPACITY: N/A (Retired) COMMITTEE (Retired) DIRECTOR, VETERANS LAND ACT (Retired) ESTATE TRUSTEE DURING LITIGATION ESTATE TRUSTEE WITH A WILL ESTATE TRUSTEE WITHOUT A WILL EXECUTOR (Retired) FIRM NAME GENERAL PARTNER JOINT ACCOUNT JOINT ACCOUNT (Retired) JOINT ACCOUNT, RIGHT OF SURVIVORSHIP JOINT TENANTS LIFE ESTATE LIFE TENANT (Retired) LIMITED PARTNERSHIP (Retired) MINISTER (OF THE CROWN) (Retired) MUNICIPAL OFFICER (Retired) OFFICIAL GUARDIAN PARTNER PARTNERSHIP (Retired) POWER OF APPOINTMENT (Retired) POWER OF ATTORNEY (Retired) PUBLIC GUARDIAN AND TRUSTEE PUBLIC TRUSTEE (Retired) REGISTERED OWNER REMAINDER REMAINDERMAN (Retired) REVERSIONER (Retired) TENANTS IN COMMON TO USES (Retired) TRUSTEE TRUSTEE FOR SALE (Retired) TRUSTEE IN BANKRUPTCY TRUSTEE, IN TRUST (Retired) French']/TD[2]/INPUT[1]")
	public WebElementFacade Name2_WebEdit;

	@FindBy(xpath = "//TR[normalize-space()='ADMINISTRATOR (Retired) ADMINISTRATOR - DE BONIS NON ADMINISTRATIS (Retired) ADMINISTRATOR WITH WILL ANNEXED (Retired) AUTHORIZED OFFICER (Retired) BENEFICIAL OWNER (Retired) CAPACITY: N/A (Retired) COMMITTEE (Retired) DIRECTOR, VETERANS LAND ACT (Retired) ESTATE TRUSTEE DURING LITIGATION ESTATE TRUSTEE WITH A WILL ESTATE TRUSTEE WITHOUT A WILL EXECUTOR (Retired) FIRM NAME GENERAL PARTNER JOINT ACCOUNT JOINT ACCOUNT (Retired) JOINT ACCOUNT, RIGHT OF SURVIVORSHIP JOINT TENANTS LIFE ESTATE LIFE TENANT (Retired) LIMITED PARTNERSHIP (Retired) MINISTER (OF THE CROWN) (Retired) MUNICIPAL OFFICER (Retired) OFFICIAL GUARDIAN PARTNER PARTNERSHIP (Retired) POWER OF APPOINTMENT (Retired) POWER OF ATTORNEY (Retired) PUBLIC GUARDIAN AND TRUSTEE PUBLIC TRUSTEE (Retired) REGISTERED OWNER REMAINDER REMAINDERMAN (Retired) REVERSIONER (Retired) TENANTS IN COMMON TO USES (Retired) TRUSTEE TRUSTEE FOR SALE (Retired) TRUSTEE IN BANKRUPTCY TRUSTEE, IN TRUST (Retired) French']/TD[1]/INPUT[1]")
	public WebElementFacade Owner1_WebCheckBox;

	@FindBy(xpath = "//INPUT[@id='removeSelectedBulkOwnerRows']")
	public WebElementFacade RemoveSelected_Bulk_WebButton;

	@FindBy(xpath = "//input[@value='Remove Selected' and @id='ownersForm.remove']")
	public WebElementFacade RemoveSelected_WebButton;

	@FindBy(xpath = "//TR[normalize-space()='ADMINISTRATOR (Retired) ADMINISTRATOR - DE BONIS NON ADMINISTRATIS (Retired) ADMINISTRATOR WITH WILL ANNEXED (Retired) AUTHORIZED OFFICER (Retired) BENEFICIAL OWNER (Retired) CAPACITY: N/A (Retired) COMMITTEE (Retired) DIRECTOR, VETERANS LAND ACT (Retired) ESTATE TRUSTEE DURING LITIGATION ESTATE TRUSTEE WITH A WILL ESTATE TRUSTEE WITHOUT A WILL EXECUTOR (Retired) FIRM NAME GENERAL PARTNER JOINT ACCOUNT JOINT ACCOUNT (Retired) JOINT ACCOUNT, RIGHT OF SURVIVORSHIP JOINT TENANTS LIFE ESTATE LIFE TENANT (Retired) LIMITED PARTNERSHIP (Retired) MINISTER (OF THE CROWN) (Retired) MUNICIPAL OFFICER (Retired) OFFICIAL GUARDIAN PARTNER PARTNERSHIP (Retired) POWER OF APPOINTMENT (Retired) POWER OF ATTORNEY (Retired) PUBLIC GUARDIAN AND TRUSTEE PUBLIC TRUSTEE (Retired) REGISTERED OWNER REMAINDER REMAINDERMAN (Retired) REVERSIONER (Retired) TENANTS IN COMMON TO USES (Retired) TRUSTEE TRUSTEE FOR SALE (Retired) TRUSTEE IN BANKRUPTCY TRUSTEE, IN TRUST (Retired) French']/TD[5]/INPUT[1]")
	public WebElementFacade Share2_WebEdit;

	@FindBy(xpath = "//input[@id='ApplyToAllBtnForOwners' and @value='Apply to All']")
	public WebElementFacade ApplyToAll_WebButton;

}
